### ISSUE TITLE
Failed to resolve: com.github.barteksc:android-pdf-viewer:3.2.0-beta.1

### ISSUE THREAD

**Issue by arunpk89** [DImuthuUpe/AndroidPdfViewer#1208]
Please anyone give me a solution. 
some comments are add mavenCentral() in the gradle. I have added this also but facing same issue

**Comment by abir-cse** [comment]
Change it to : 
`implementation 'com.github.DImuthuUpe:AndroidPdfViewer:3.1.0-beta.1'`

**Comment by arunpk89** [comment]
replaced the previous implemtation with below. That fixed my issue
    implementation 'com.github.barteksc:AndroidPdfViewer:master-SNAPSHOT'
